name: Run .NET Application

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Choose the flavor'
        required: true
        default: 'chocolate'
      environment:
        description: 'Select environment'
        required: true
        default: 'staging'
      version:
        description: 'Enter version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0'

      - name: Run .NET Application
        run: |
          echo "Flavor: ${{ inputs.flavor }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Version: ${{ inputs.version }}"
          # Correct the argument format, without the equals sign
          dotnet run --project .\ConsoleApp\ConsoleApp.csproj -f "${{ inputs.flavor }}" -e "${{ inputs.environment }}" -v "${{ inputs.version }}"
        shell: pwsh
