name: Showcase problem with windows-2025 image

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Choose the flavor'
        required: true
        default: 'chocolate'
      environment:
        description: 'Select environment'
        required: true
        default: 'staging'
      version:
        description: 'Enter version'
        required: true
        default: '1.0.0'
jobs:
  upload-setup-artifact:
    runs-on: windows-2025
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
      - name: Build
        run: dotnet build
    

      - name: Run .NET Application
        run: |
          echo "Flavor: ${{ inputs.flavor }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Version: ${{ inputs.version }}"
          # Correct the argument format, without the equals sign
          dotnet run --project .\ConsoleApp\ConsoleApp.csproj -f "${{ inputs.flavor }}" -e "${{ inputs.environment }}" -v "${{ inputs.version }}"
        shell: pwsh
